### ISSUE TITLE
Unhelpful error when using nengo.Network instead of spa.Network

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#174]
When accidentally using `nengo.Network` instead of `spa.Network` it is possible to get an error that does not really point at the problem.

Try this code:
```python
import nengo
import nengo_spa as spa

model = nengo.Network()
with model:
    state = spa.State(16)
    state2 = spa.State(16)
    state >> state2
```

The error will be:
```
Traceback (most recent call last):
  File "/Volumes/Home/blubb/Library/Python/3.6/lib/python/site-packages/nengo_gui/page.py", line 220, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 8, in <module>
  File "/Volumes/Home/blubb/Library/Python/3.6/lib/python/site-packages/nengo_spa/network.py", line 117, in __rshift__
    return as_ast_node(self) >> as_sink(other)
  File "/Volumes/Home/blubb/Library/Python/3.6/lib/python/site-packages/nengo_spa/actions.py", line 38, in __rrshift__
    infer_types(self, other)
  File "/Volumes/Home/blubb/Library/Python/3.6/lib/python/site-packages/nengo_spa/ast/base.py", line 14, in infer_types
    type_ = coerce_types(*[n.type for n in nodes])
  File "/Volumes/Home/blubb/Library/Python/3.6/lib/python/site-packages/nengo_spa/types.py", line 157, in coerce_types
    raise SpaTypeError(reason + ": " + ", ".join(str(t) for t in types))
nengo_spa.exceptions.SpaTypeError: Different vocabularies: TVocabulary<16-dimensional vocab at 0x10dedf780>, TVocabulary<16-dimensional vocab at 0x10dedf2b0>
```

**Comment by Seanny123** [comment]
Any ideas as to how this could be solved? The only solution I can think of is checking if the two modules have the same parent and the parent network isn't a `spa.Network`. Can the SPA modules somehow keep track of the type of their parent network?

Alternatively, is there something we could do with the vocab checking to identify whether an object has been assigned a different default vocab despite having the same dimensionality as a previous object?

**Comment by jgosmann** [comment]
> Any ideas as to how this could be solved?

I thought about some possibilities, but haven't found anything I'm satisfied with. I have to think about your ideas.



> Can the SPA modules somehow keep track of the type of their parent network?

They could, but we probably don't want to for the same reasons that Nengo isn't keeping track of parent networks.
